//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_exceladEntities : DbContext
    {
        public db_exceladEntities()
            : base("name=db_exceladEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_COURSE> TBL_COURSE { get; set; }
        public virtual DbSet<TBL_SUBJECTS> TBL_SUBJECTS { get; set; }
        public virtual DbSet<TBL_ENQUIRY> TBL_ENQUIRY { get; set; }
        public virtual DbSet<TBL_ADMISSION> TBL_ADMISSION { get; set; }
        public virtual DbSet<TBL_BRANCH> TBL_BRANCH { get; set; }
        public virtual DbSet<TBL_DESIGNATION> TBL_DESIGNATION { get; set; }
        public virtual DbSet<TBL_USERS> TBL_USERS { get; set; }
    }
}
