//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADMISSION
    {
        public int A_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_JOINING { get; set; }
        public string APPEARING_FOR { get; set; }
        public Nullable<int> APPEARING_YEAR { get; set; }
        public string STUDENT_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FATHER { get; set; }
        public string MOTHER { get; set; }
        public string STUDENT_CONTACT { get; set; }
        public string STUDENT_TELEGRAM { get; set; }
        public string STUDENT_EMAIL { get; set; }
        public string PARENT_CONTACT { get; set; }
        public string PARENT_TELEGRAM { get; set; }
        public string PARENT_EMAIL { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string PERMANENT_DISTRICT { get; set; }
        public string PERMANENT_PINCODE { get; set; }
        public string RESIDENTIAL_ADDRESS { get; set; }
        public string RESIDENTIAL_DISTRICT { get; set; }
        public string RESIDENTIAL_PINCODE { get; set; }
        public Nullable<decimal> MARKS_10TH { get; set; }
        public Nullable<decimal> MARKS_11TH { get; set; }
        public Nullable<decimal> MARKS_12TH { get; set; }
        public Nullable<bool> MEDIUM { get; set; }
        public string SCHOOL_COLLLEGE { get; set; }
        public Nullable<int> CAME_THROUGH_ID { get; set; }
        public Nullable<int> TOTAL_FEES { get; set; }
        public Nullable<decimal> DISCOUNT_PERCENT { get; set; }
        public Nullable<decimal> DISCOUNT_RUPEES { get; set; }
        public Nullable<bool> PART_PAYMENT { get; set; }
        public Nullable<bool> FEES_PAID { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public string TRANSACTION_ID { get; set; }
        public Nullable<decimal> PAID_AMOUNT { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public int USER_ID { get; set; }
    
        public virtual TBL_USERS TBL_USERS { get; set; }
    }
}
