//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COURSE
    {
        public int COURSE_ID { get; set; }
        public string COURSE { get; set; }
        public Nullable<int> OFFLINE_FEES { get; set; }
        public Nullable<int> ONLINE_FEES { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
