//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string BRANCH { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CONTACT1 { get; set; }
        public string CONTACT2 { get; set; }
        public string EMAIL_ID { get; set; }
        public string ADDRESS { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
